//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace DomainModel.SearchRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SearchSoap", Namespace="http://www.stellent.com/Search/")]
    public partial class Search : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QuickSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdvancedSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback NavigationSearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Search() {
            this.Url = global::DomainModel.Properties.Settings.Default.DomainModel_SearchRef_Search;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QuickSearchCompletedEventHandler QuickSearchCompleted;
        
        /// <remarks/>
        public event AdvancedSearchCompletedEventHandler AdvancedSearchCompleted;
        
        /// <remarks/>
        public event NavigationSearchCompletedEventHandler NavigationSearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.stellent.com/Search/", RequestNamespace="http://www.stellent.com/Search/", ResponseNamespace="http://www.stellent.com/Search/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public QuickSearchResult QuickSearch(string queryText, [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)] IdcProperty[] extraProps) {
            object[] results = this.Invoke("QuickSearch", new object[] {
                        queryText,
                        extraProps});
            return ((QuickSearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void QuickSearchAsync(string queryText, IdcProperty[] extraProps) {
            this.QuickSearchAsync(queryText, extraProps, null);
        }
        
        /// <remarks/>
        public void QuickSearchAsync(string queryText, IdcProperty[] extraProps, object userState) {
            if ((this.QuickSearchOperationCompleted == null)) {
                this.QuickSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuickSearchOperationCompleted);
            }
            this.InvokeAsync("QuickSearch", new object[] {
                        queryText,
                        extraProps}, this.QuickSearchOperationCompleted, userState);
        }
        
        private void OnQuickSearchOperationCompleted(object arg) {
            if ((this.QuickSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuickSearchCompleted(this, new QuickSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.stellent.com/Search/", RequestNamespace="http://www.stellent.com/Search/", ResponseNamespace="http://www.stellent.com/Search/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AdvancedSearchResult AdvancedSearch(string queryText, string sortField, string sortOrder, int resultCount, [System.Xml.Serialization.XmlIgnoreAttribute()] bool resultCountSpecified, [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)] IdcProperty[] extraProps) {
            object[] results = this.Invoke("AdvancedSearch", new object[] {
                        queryText,
                        sortField,
                        sortOrder,
                        resultCount,
                        resultCountSpecified,
                        extraProps});
            return ((AdvancedSearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void AdvancedSearchAsync(string queryText, string sortField, string sortOrder, int resultCount, bool resultCountSpecified, IdcProperty[] extraProps) {
            this.AdvancedSearchAsync(queryText, sortField, sortOrder, resultCount, resultCountSpecified, extraProps, null);
        }
        
        /// <remarks/>
        public void AdvancedSearchAsync(string queryText, string sortField, string sortOrder, int resultCount, bool resultCountSpecified, IdcProperty[] extraProps, object userState) {
            if ((this.AdvancedSearchOperationCompleted == null)) {
                this.AdvancedSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdvancedSearchOperationCompleted);
            }
            this.InvokeAsync("AdvancedSearch", new object[] {
                        queryText,
                        sortField,
                        sortOrder,
                        resultCount,
                        resultCountSpecified,
                        extraProps}, this.AdvancedSearchOperationCompleted, userState);
        }
        
        private void OnAdvancedSearchOperationCompleted(object arg) {
            if ((this.AdvancedSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdvancedSearchCompleted(this, new AdvancedSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.stellent.com/Search/", RequestNamespace="http://www.stellent.com/Search/", ResponseNamespace="http://www.stellent.com/Search/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NavigationSearchResult NavigationSearch(string queryText, string sortField, string sortOrder, int resultCount, [System.Xml.Serialization.XmlIgnoreAttribute()] bool resultCountSpecified, int pageNumber, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageNumberSpecified, int startRow, [System.Xml.Serialization.XmlIgnoreAttribute()] bool startRowSpecified, int endRow, [System.Xml.Serialization.XmlIgnoreAttribute()] bool endRowSpecified, [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)] IdcProperty[] extraProps) {
            object[] results = this.Invoke("NavigationSearch", new object[] {
                        queryText,
                        sortField,
                        sortOrder,
                        resultCount,
                        resultCountSpecified,
                        pageNumber,
                        pageNumberSpecified,
                        startRow,
                        startRowSpecified,
                        endRow,
                        endRowSpecified,
                        extraProps});
            return ((NavigationSearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void NavigationSearchAsync(string queryText, string sortField, string sortOrder, int resultCount, bool resultCountSpecified, int pageNumber, bool pageNumberSpecified, int startRow, bool startRowSpecified, int endRow, bool endRowSpecified, IdcProperty[] extraProps) {
            this.NavigationSearchAsync(queryText, sortField, sortOrder, resultCount, resultCountSpecified, pageNumber, pageNumberSpecified, startRow, startRowSpecified, endRow, endRowSpecified, extraProps, null);
        }
        
        /// <remarks/>
        public void NavigationSearchAsync(string queryText, string sortField, string sortOrder, int resultCount, bool resultCountSpecified, int pageNumber, bool pageNumberSpecified, int startRow, bool startRowSpecified, int endRow, bool endRowSpecified, IdcProperty[] extraProps, object userState) {
            if ((this.NavigationSearchOperationCompleted == null)) {
                this.NavigationSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNavigationSearchOperationCompleted);
            }
            this.InvokeAsync("NavigationSearch", new object[] {
                        queryText,
                        sortField,
                        sortOrder,
                        resultCount,
                        resultCountSpecified,
                        pageNumber,
                        pageNumberSpecified,
                        startRow,
                        startRowSpecified,
                        endRow,
                        endRowSpecified,
                        extraProps}, this.NavigationSearchOperationCompleted, userState);
        }
        
        private void OnNavigationSearchOperationCompleted(object arg) {
            if ((this.NavigationSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NavigationSearchCompleted(this, new NavigationSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/Search/")]
    public partial class IdcProperty {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/Search/")]
    public partial class NavigationSearchResult {
        
        private SearchResults[] searchResultsField;
        
        private SearchInfo searchInfoField;
        
        private NavigationPages[] navigationPagesField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SearchResults")]
        public SearchResults[] SearchResults {
            get {
                return this.searchResultsField;
            }
            set {
                this.searchResultsField = value;
            }
        }
        
        /// <remarks/>
        public SearchInfo SearchInfo {
            get {
                return this.searchInfoField;
            }
            set {
                this.searchInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NavigationPages")]
        public NavigationPages[] NavigationPages {
            get {
                return this.navigationPagesField;
            }
            set {
                this.navigationPagesField = value;
            }
        }
        
        /// <remarks/>
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/Search/")]
    public partial class SearchResults {
        
        private int dIDField;
        
        private bool dIDFieldSpecified;
        
        private int dRevisionIDField;
        
        private bool dRevisionIDFieldSpecified;
        
        private string dDocNameField;
        
        private string dDocTitleField;
        
        private string dDocTypeField;
        
        private string dDocAuthorField;
        
        private string dSecurityGroupField;
        
        private string dDocAccountField;
        
        private int xLichnost_IDField;
        
        private bool xLichnost_IDFieldSpecified;
        
        private string dExtensionField;
        
        private string dWebExtensionField;
        
        private string dRevLabelField;
        
        private string dInDateField;
        
        private string dOutDateField;
        
        private string dFormatField;
        
        private string dOriginalNameField;
        
        private string urlField;
        
        private string webCgiRootField;
        
        private string dGifField;
        
        private int webFileSizeField;
        
        private bool webFileSizeFieldSpecified;
        
        private int vaultFileSizeField;
        
        private bool vaultFileSizeFieldSpecified;
        
        private int alternateFileSizeField;
        
        private bool alternateFileSizeFieldSpecified;
        
        private string alternateFormatField;
        
        private string dPublishTypeField;
        
        private string dRendition1Field;
        
        private string dRendition2Field;
        
        private IdcProperty[] customDocMetaDataField;
        
        /// <remarks/>
        public int dID {
            get {
                return this.dIDField;
            }
            set {
                this.dIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIDSpecified {
            get {
                return this.dIDFieldSpecified;
            }
            set {
                this.dIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int dRevisionID {
            get {
                return this.dRevisionIDField;
            }
            set {
                this.dRevisionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevisionIDSpecified {
            get {
                return this.dRevisionIDFieldSpecified;
            }
            set {
                this.dRevisionIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string dDocName {
            get {
                return this.dDocNameField;
            }
            set {
                this.dDocNameField = value;
            }
        }
        
        /// <remarks/>
        public string dDocTitle {
            get {
                return this.dDocTitleField;
            }
            set {
                this.dDocTitleField = value;
            }
        }
        
        /// <remarks/>
        public string dDocType {
            get {
                return this.dDocTypeField;
            }
            set {
                this.dDocTypeField = value;
            }
        }
        
        /// <remarks/>
        public string dDocAuthor {
            get {
                return this.dDocAuthorField;
            }
            set {
                this.dDocAuthorField = value;
            }
        }
        
        /// <remarks/>
        public string dSecurityGroup {
            get {
                return this.dSecurityGroupField;
            }
            set {
                this.dSecurityGroupField = value;
            }
        }
        
        /// <remarks/>
        public string dDocAccount {
            get {
                return this.dDocAccountField;
            }
            set {
                this.dDocAccountField = value;
            }
        }
        
        /// <remarks/>
        public int xLichnost_ID {
            get {
                return this.xLichnost_IDField;
            }
            set {
                this.xLichnost_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xLichnost_IDSpecified {
            get {
                return this.xLichnost_IDFieldSpecified;
            }
            set {
                this.xLichnost_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string dExtension {
            get {
                return this.dExtensionField;
            }
            set {
                this.dExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string dWebExtension {
            get {
                return this.dWebExtensionField;
            }
            set {
                this.dWebExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string dRevLabel {
            get {
                return this.dRevLabelField;
            }
            set {
                this.dRevLabelField = value;
            }
        }
        
        /// <remarks/>
        public string dInDate {
            get {
                return this.dInDateField;
            }
            set {
                this.dInDateField = value;
            }
        }
        
        /// <remarks/>
        public string dOutDate {
            get {
                return this.dOutDateField;
            }
            set {
                this.dOutDateField = value;
            }
        }
        
        /// <remarks/>
        public string dFormat {
            get {
                return this.dFormatField;
            }
            set {
                this.dFormatField = value;
            }
        }
        
        /// <remarks/>
        public string dOriginalName {
            get {
                return this.dOriginalNameField;
            }
            set {
                this.dOriginalNameField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string webCgiRoot {
            get {
                return this.webCgiRootField;
            }
            set {
                this.webCgiRootField = value;
            }
        }
        
        /// <remarks/>
        public string dGif {
            get {
                return this.dGifField;
            }
            set {
                this.dGifField = value;
            }
        }
        
        /// <remarks/>
        public int webFileSize {
            get {
                return this.webFileSizeField;
            }
            set {
                this.webFileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool webFileSizeSpecified {
            get {
                return this.webFileSizeFieldSpecified;
            }
            set {
                this.webFileSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int vaultFileSize {
            get {
                return this.vaultFileSizeField;
            }
            set {
                this.vaultFileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vaultFileSizeSpecified {
            get {
                return this.vaultFileSizeFieldSpecified;
            }
            set {
                this.vaultFileSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int alternateFileSize {
            get {
                return this.alternateFileSizeField;
            }
            set {
                this.alternateFileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool alternateFileSizeSpecified {
            get {
                return this.alternateFileSizeFieldSpecified;
            }
            set {
                this.alternateFileSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string alternateFormat {
            get {
                return this.alternateFormatField;
            }
            set {
                this.alternateFormatField = value;
            }
        }
        
        /// <remarks/>
        public string dPublishType {
            get {
                return this.dPublishTypeField;
            }
            set {
                this.dPublishTypeField = value;
            }
        }
        
        /// <remarks/>
        public string dRendition1 {
            get {
                return this.dRendition1Field;
            }
            set {
                this.dRendition1Field = value;
            }
        }
        
        /// <remarks/>
        public string dRendition2 {
            get {
                return this.dRendition2Field;
            }
            set {
                this.dRendition2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public IdcProperty[] CustomDocMetaData {
            get {
                return this.customDocMetaDataField;
            }
            set {
                this.customDocMetaDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/Search/")]
    public partial class SearchInfo {
        
        private int startRowField;
        
        private bool startRowFieldSpecified;
        
        private int endRowField;
        
        private bool endRowFieldSpecified;
        
        private int pageNumberField;
        
        private bool pageNumberFieldSpecified;
        
        private int numPagesField;
        
        private bool numPagesFieldSpecified;
        
        private int totalRowsField;
        
        private bool totalRowsFieldSpecified;
        
        private int totalDocsProcessedField;
        
        private bool totalDocsProcessedFieldSpecified;
        
        /// <remarks/>
        public int startRow {
            get {
                return this.startRowField;
            }
            set {
                this.startRowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startRowSpecified {
            get {
                return this.startRowFieldSpecified;
            }
            set {
                this.startRowFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int endRow {
            get {
                return this.endRowField;
            }
            set {
                this.endRowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endRowSpecified {
            get {
                return this.endRowFieldSpecified;
            }
            set {
                this.endRowFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumberSpecified {
            get {
                return this.pageNumberFieldSpecified;
            }
            set {
                this.pageNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int numPages {
            get {
                return this.numPagesField;
            }
            set {
                this.numPagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numPagesSpecified {
            get {
                return this.numPagesFieldSpecified;
            }
            set {
                this.numPagesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int totalRows {
            get {
                return this.totalRowsField;
            }
            set {
                this.totalRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalRowsSpecified {
            get {
                return this.totalRowsFieldSpecified;
            }
            set {
                this.totalRowsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int totalDocsProcessed {
            get {
                return this.totalDocsProcessedField;
            }
            set {
                this.totalDocsProcessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalDocsProcessedSpecified {
            get {
                return this.totalDocsProcessedFieldSpecified;
            }
            set {
                this.totalDocsProcessedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/Search/")]
    public partial class NavigationPages {
        
        private int headerPageNumberField;
        
        private bool headerPageNumberFieldSpecified;
        
        private int pageReferenceField;
        
        private bool pageReferenceFieldSpecified;
        
        private int pageNumberField;
        
        private bool pageNumberFieldSpecified;
        
        private int startRowField;
        
        private bool startRowFieldSpecified;
        
        private int endRowField;
        
        private bool endRowFieldSpecified;
        
        /// <remarks/>
        public int headerPageNumber {
            get {
                return this.headerPageNumberField;
            }
            set {
                this.headerPageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool headerPageNumberSpecified {
            get {
                return this.headerPageNumberFieldSpecified;
            }
            set {
                this.headerPageNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int pageReference {
            get {
                return this.pageReferenceField;
            }
            set {
                this.pageReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageReferenceSpecified {
            get {
                return this.pageReferenceFieldSpecified;
            }
            set {
                this.pageReferenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumberSpecified {
            get {
                return this.pageNumberFieldSpecified;
            }
            set {
                this.pageNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int startRow {
            get {
                return this.startRowField;
            }
            set {
                this.startRowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startRowSpecified {
            get {
                return this.startRowFieldSpecified;
            }
            set {
                this.startRowFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int endRow {
            get {
                return this.endRowField;
            }
            set {
                this.endRowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endRowSpecified {
            get {
                return this.endRowFieldSpecified;
            }
            set {
                this.endRowFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/Search/")]
    public partial class StatusInfo {
        
        private int statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string statusMessageField;
        
        /// <remarks/>
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/Search/")]
    public partial class AdvancedSearchResult {
        
        private SearchResults[] searchResultsField;
        
        private SearchInfo searchInfoField;
        
        private NavigationPages[] navigationPagesField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SearchResults")]
        public SearchResults[] SearchResults {
            get {
                return this.searchResultsField;
            }
            set {
                this.searchResultsField = value;
            }
        }
        
        /// <remarks/>
        public SearchInfo SearchInfo {
            get {
                return this.searchInfoField;
            }
            set {
                this.searchInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NavigationPages")]
        public NavigationPages[] NavigationPages {
            get {
                return this.navigationPagesField;
            }
            set {
                this.navigationPagesField = value;
            }
        }
        
        /// <remarks/>
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/Search/")]
    public partial class QuickSearchResult {
        
        private SearchResults[] searchResultsField;
        
        private SearchInfo searchInfoField;
        
        private NavigationPages[] navigationPagesField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SearchResults")]
        public SearchResults[] SearchResults {
            get {
                return this.searchResultsField;
            }
            set {
                this.searchResultsField = value;
            }
        }
        
        /// <remarks/>
        public SearchInfo SearchInfo {
            get {
                return this.searchInfoField;
            }
            set {
                this.searchInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NavigationPages")]
        public NavigationPages[] NavigationPages {
            get {
                return this.navigationPagesField;
            }
            set {
                this.navigationPagesField = value;
            }
        }
        
        /// <remarks/>
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QuickSearchCompletedEventHandler(object sender, QuickSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuickSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuickSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QuickSearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QuickSearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AdvancedSearchCompletedEventHandler(object sender, AdvancedSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdvancedSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdvancedSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AdvancedSearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdvancedSearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NavigationSearchCompletedEventHandler(object sender, NavigationSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NavigationSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NavigationSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NavigationSearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NavigationSearchResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591