//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace DomainModel.MetaDataRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MetaDataSoap", Namespace="http://www.stellent.com/MetaData/")]
    public partial class MetaData : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DocMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserMetaDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MetaData() {
            this.Url = global::DomainModel.Properties.Settings.Default.DomainModel_DocInfoRef_DocInfo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DocMetaDataCompletedEventHandler DocMetaDataCompleted;
        
        /// <remarks/>
        public event UserMetaDataCompletedEventHandler UserMetaDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.stellent.com/MetaData/", RequestNamespace="http://www.stellent.com/MetaData/", ResponseNamespace="http://www.stellent.com/MetaData/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DocMetaDataResult DocMetaData(int privilege, [System.Xml.Serialization.XmlIgnoreAttribute()] bool privilegeSpecified, [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)] IdcProperty[] extraProps) {
            object[] results = this.Invoke("DocMetaData", new object[] {
                        privilege,
                        privilegeSpecified,
                        extraProps});
            return ((DocMetaDataResult)(results[0]));
        }
        
        /// <remarks/>
        public void DocMetaDataAsync(int privilege, bool privilegeSpecified, IdcProperty[] extraProps) {
            this.DocMetaDataAsync(privilege, privilegeSpecified, extraProps, null);
        }
        
        /// <remarks/>
        public void DocMetaDataAsync(int privilege, bool privilegeSpecified, IdcProperty[] extraProps, object userState) {
            if ((this.DocMetaDataOperationCompleted == null)) {
                this.DocMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocMetaDataOperationCompleted);
            }
            this.InvokeAsync("DocMetaData", new object[] {
                        privilege,
                        privilegeSpecified,
                        extraProps}, this.DocMetaDataOperationCompleted, userState);
        }
        
        private void OnDocMetaDataOperationCompleted(object arg) {
            if ((this.DocMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocMetaDataCompleted(this, new DocMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.stellent.com/MetaData/", RequestNamespace="http://www.stellent.com/MetaData/", ResponseNamespace="http://www.stellent.com/MetaData/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserMetaDataResult UserMetaData([System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)] IdcProperty[] extraProps) {
            object[] results = this.Invoke("UserMetaData", new object[] {
                        extraProps});
            return ((UserMetaDataResult)(results[0]));
        }
        
        /// <remarks/>
        public void UserMetaDataAsync(IdcProperty[] extraProps) {
            this.UserMetaDataAsync(extraProps, null);
        }
        
        /// <remarks/>
        public void UserMetaDataAsync(IdcProperty[] extraProps, object userState) {
            if ((this.UserMetaDataOperationCompleted == null)) {
                this.UserMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserMetaDataOperationCompleted);
            }
            this.InvokeAsync("UserMetaData", new object[] {
                        extraProps}, this.UserMetaDataOperationCompleted, userState);
        }
        
        private void OnUserMetaDataOperationCompleted(object arg) {
            if ((this.UserMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserMetaDataCompleted(this, new UserMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/MetaData/")]
    public partial class IdcProperty {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/MetaData/")]
    public partial class UserMetaFields {
        
        private string umdNameField;
        
        private string umdTypeField;
        
        private string umdCaptionField;
        
        private bool umdIsOptionListField;
        
        private bool umdIsOptionListFieldSpecified;
        
        private string umdOptionListTypeField;
        
        private string umdOptionListKeyField;
        
        private bool umdIsAdminEditField;
        
        private bool umdIsAdminEditFieldSpecified;
        
        private bool umdIsViewOnlyField;
        
        private bool umdIsViewOnlyFieldSpecified;
        
        private string umdOverrideBitFlagField;
        
        private string umdOptionListValuesField;
        
        /// <remarks/>
        public string umdName {
            get {
                return this.umdNameField;
            }
            set {
                this.umdNameField = value;
            }
        }
        
        /// <remarks/>
        public string umdType {
            get {
                return this.umdTypeField;
            }
            set {
                this.umdTypeField = value;
            }
        }
        
        /// <remarks/>
        public string umdCaption {
            get {
                return this.umdCaptionField;
            }
            set {
                this.umdCaptionField = value;
            }
        }
        
        /// <remarks/>
        public bool umdIsOptionList {
            get {
                return this.umdIsOptionListField;
            }
            set {
                this.umdIsOptionListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool umdIsOptionListSpecified {
            get {
                return this.umdIsOptionListFieldSpecified;
            }
            set {
                this.umdIsOptionListFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string umdOptionListType {
            get {
                return this.umdOptionListTypeField;
            }
            set {
                this.umdOptionListTypeField = value;
            }
        }
        
        /// <remarks/>
        public string umdOptionListKey {
            get {
                return this.umdOptionListKeyField;
            }
            set {
                this.umdOptionListKeyField = value;
            }
        }
        
        /// <remarks/>
        public bool umdIsAdminEdit {
            get {
                return this.umdIsAdminEditField;
            }
            set {
                this.umdIsAdminEditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool umdIsAdminEditSpecified {
            get {
                return this.umdIsAdminEditFieldSpecified;
            }
            set {
                this.umdIsAdminEditFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool umdIsViewOnly {
            get {
                return this.umdIsViewOnlyField;
            }
            set {
                this.umdIsViewOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool umdIsViewOnlySpecified {
            get {
                return this.umdIsViewOnlyFieldSpecified;
            }
            set {
                this.umdIsViewOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string umdOverrideBitFlag {
            get {
                return this.umdOverrideBitFlagField;
            }
            set {
                this.umdOverrideBitFlagField = value;
            }
        }
        
        /// <remarks/>
        public string umdOptionListValues {
            get {
                return this.umdOptionListValuesField;
            }
            set {
                this.umdOptionListValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/MetaData/")]
    public partial class UserMetaDataResult {
        
        private UserMetaFields[] userMetaFieldsField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserMetaFields")]
        public UserMetaFields[] UserMetaFields {
            get {
                return this.userMetaFieldsField;
            }
            set {
                this.userMetaFieldsField = value;
            }
        }
        
        /// <remarks/>
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/MetaData/")]
    public partial class StatusInfo {
        
        private int statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string statusMessageField;
        
        /// <remarks/>
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/MetaData/")]
    public partial class DocMetaFields {
        
        private string dNameField;
        
        private string dTypeField;
        
        private bool dIsRequiredField;
        
        private bool dIsRequiredFieldSpecified;
        
        private bool dIsEnabledField;
        
        private bool dIsEnabledFieldSpecified;
        
        private bool dIsSearchableField;
        
        private bool dIsSearchableFieldSpecified;
        
        private string dCaptionField;
        
        private bool dIsOptionListField;
        
        private bool dIsOptionListFieldSpecified;
        
        private string dOptionListKeyField;
        
        private string dDefaultValueField;
        
        private int dOrderField;
        
        private bool dOrderFieldSpecified;
        
        private string dOptionListTypeField;
        
        private string dOptionListValuesField;
        
        /// <remarks/>
        public string dName {
            get {
                return this.dNameField;
            }
            set {
                this.dNameField = value;
            }
        }
        
        /// <remarks/>
        public string dType {
            get {
                return this.dTypeField;
            }
            set {
                this.dTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool dIsRequired {
            get {
                return this.dIsRequiredField;
            }
            set {
                this.dIsRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsRequiredSpecified {
            get {
                return this.dIsRequiredFieldSpecified;
            }
            set {
                this.dIsRequiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool dIsEnabled {
            get {
                return this.dIsEnabledField;
            }
            set {
                this.dIsEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsEnabledSpecified {
            get {
                return this.dIsEnabledFieldSpecified;
            }
            set {
                this.dIsEnabledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool dIsSearchable {
            get {
                return this.dIsSearchableField;
            }
            set {
                this.dIsSearchableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsSearchableSpecified {
            get {
                return this.dIsSearchableFieldSpecified;
            }
            set {
                this.dIsSearchableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string dCaption {
            get {
                return this.dCaptionField;
            }
            set {
                this.dCaptionField = value;
            }
        }
        
        /// <remarks/>
        public bool dIsOptionList {
            get {
                return this.dIsOptionListField;
            }
            set {
                this.dIsOptionListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsOptionListSpecified {
            get {
                return this.dIsOptionListFieldSpecified;
            }
            set {
                this.dIsOptionListFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string dOptionListKey {
            get {
                return this.dOptionListKeyField;
            }
            set {
                this.dOptionListKeyField = value;
            }
        }
        
        /// <remarks/>
        public string dDefaultValue {
            get {
                return this.dDefaultValueField;
            }
            set {
                this.dDefaultValueField = value;
            }
        }
        
        /// <remarks/>
        public int dOrder {
            get {
                return this.dOrderField;
            }
            set {
                this.dOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dOrderSpecified {
            get {
                return this.dOrderFieldSpecified;
            }
            set {
                this.dOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string dOptionListType {
            get {
                return this.dOptionListTypeField;
            }
            set {
                this.dOptionListTypeField = value;
            }
        }
        
        /// <remarks/>
        public string dOptionListValues {
            get {
                return this.dOptionListValuesField;
            }
            set {
                this.dOptionListValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/MetaData/")]
    public partial class DocTypes {
        
        private string dDocTypeField;
        
        private string dDescriptionField;
        
        private string dGifField;
        
        /// <remarks/>
        public string dDocType {
            get {
                return this.dDocTypeField;
            }
            set {
                this.dDocTypeField = value;
            }
        }
        
        /// <remarks/>
        public string dDescription {
            get {
                return this.dDescriptionField;
            }
            set {
                this.dDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string dGif {
            get {
                return this.dGifField;
            }
            set {
                this.dGifField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/MetaData/")]
    public partial class DocMetaDataResult {
        
        private bool isAutoNumberField;
        
        private bool isAutoNumberFieldSpecified;
        
        private bool useAccountsField;
        
        private bool useAccountsFieldSpecified;
        
        private DocTypes[] docTypesField;
        
        private string[] securityGroupsField;
        
        private string[] accountsField;
        
        private DocMetaFields[] docMetaFieldsField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        public bool isAutoNumber {
            get {
                return this.isAutoNumberField;
            }
            set {
                this.isAutoNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isAutoNumberSpecified {
            get {
                return this.isAutoNumberFieldSpecified;
            }
            set {
                this.isAutoNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool useAccounts {
            get {
                return this.useAccountsField;
            }
            set {
                this.useAccountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useAccountsSpecified {
            get {
                return this.useAccountsFieldSpecified;
            }
            set {
                this.useAccountsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocTypes")]
        public DocTypes[] DocTypes {
            get {
                return this.docTypesField;
            }
            set {
                this.docTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("option", IsNullable=false)]
        public string[] SecurityGroups {
            get {
                return this.securityGroupsField;
            }
            set {
                this.securityGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("option", IsNullable=false)]
        public string[] Accounts {
            get {
                return this.accountsField;
            }
            set {
                this.accountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocMetaFields")]
        public DocMetaFields[] DocMetaFields {
            get {
                return this.docMetaFieldsField;
            }
            set {
                this.docMetaFieldsField = value;
            }
        }
        
        /// <remarks/>
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DocMetaDataCompletedEventHandler(object sender, DocMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DocMetaDataResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DocMetaDataResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UserMetaDataCompletedEventHandler(object sender, UserMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserMetaDataResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserMetaDataResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591